baseurl: "/personal-eportfolio"
url: "https://github.com/aristotelissym/personal-eportfolio"

title: "Aristotelis Symeonidis e-Portfolio"
description: "This is my Personal Website"

author-name: "Aristotelis Symeonidis"